
# Load the required packages ----------------------------------------------

library(shiny)
library(rhandsontable)
library(bslib) # theme
library(tidyverse)
library(openxlsx)

# Create two containers ---------------------------------------------------

## Card 1 - Original Data --------------------------------------------------

card1 <- card(
  full_screen = TRUE,
  # Header
  card_header(div(style = "text-align: center;", tags$b("Original Data"))),
  # Dimension
  h6(tags$b("Table Info.")),
  textInput(inputId = "n_tb", label = "- Number of tables", value = 6),
  p("- Dimension"),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -15px;",
    textInput(inputId = "col", label = "Column", value = 12),
    textInput(inputId = "row", label = "Row", value = 8)
  ),
  # Variable
  h6(tags$b("Variable Info.")),
  div(style = "margin-top: -20px"),
  textInput(inputId = "n_var", label = "- Number of variables", value = 4),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -10px;",
    uiOutput("var_no_ui"),
    uiOutput("var_nms_ui"),
    uiOutput("var_tps_ui")
  ),
  # Input data
  h6(tags$b("Input Data:")),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -10px;",
    uiOutput("tb_no_ui"),
    uiOutput("var_slt_ui")
  ),
  uiOutput("var_layout_ui"),
  # Confirm the input
  div(style = "margin-top: 10px"), 
  div(style = "text-align: right;",
      actionButton(inputId = "Trsfm_Butn",
                   label = "Transform it!"))
)

## Card 2 - Tidy Format ----------------------------------------------------

card2 <- navset_card_tab(
  full_screen = TRUE,
  # Header
  title = tags$b("Tidy Format"),
  nav_panel(
    title = "Tidy Data",
    # Inspect the results:
    h6(tags$b("Tidy Table")),
    DT::dataTableOutput("tidy_tb") %>% shinycssloaders::withSpinner(), 
    # Download the table:
    uiOutput(outputId = "dl")
  ),
  nav_panel(
    title = "For IGGYPOPseq", 
    ## Tidy data:
    radioButtons(inputId = "tdy_opt",
                 label = h6(tags$b("- Tidy Format Data Source:")),
                 choices = c("Generated by the app" = "tdy_gnrt",
                             "Upload the file" = "tdy_upld"),
                 selected = "tdy_gnrt",
                 inline = TRUE),
    conditionalPanel(condition = "input.tdy_opt == 'tdy_upld'", 
                     fileInput(inputId = "file", 
                               label = h6("Choose the File:")), 
                     div(style = "margin-top: -30px")
    ), 
    
    ## Reference data:
    #div(style = "margin-top: 10px"), 
    fileInput(inputId = "ref_file", 
              label = h6(tags$b("- Reference Data:"))),
    div(style = "margin-top: -30px"), 
    radioButtons(inputId = "cds_opt",
                 label = h6("CDS:"),
                 choices = c("Yes" = "y",
                             "No" = "n"),
                 selected = "n",
                 inline = TRUE),
    
    ## Primer data:
    selectInput(inputId = "prr_plt", 
                label = h6(tags$b("- Select the Target Vector:")), 
                choices = c("pPOP" = "pop",
                            "pPlantPOP" = "pltpop")
                ), 
    div(style = "margin-top: -20px"), 
    div(style = "text-align: right;",
        actionButton(inputId = "Gnrt_Butn",
                     label = "Generate")), 
    # Inspect the results:
    h6(tags$b("- Sample Info:")),
    DT::dataTableOutput("iggypop_smp_info") %>% shinycssloaders::withSpinner(), 
    # Download the table:
    uiOutput(outputId = "iggypop_dl")
  )
)

# Arrange both cards ------------------------------------------------------

page_fillable(
    
  # Theme
  theme = bs_theme(bootswatch = "minty"),

  # Application title
  titlePanel(div(style = "text-align: center;", "Tidy Buddy")),
  
  layout_column_wrap(
    width = 1/2,
    card1, card2
  ),
  h6(tags$b("Source code:")),
  div(style = "margin-top: -40px"), 
  p("The source code, along with the example data, is available via the GitHub repository (", a(href = "https://github.com/ZenanXing/Tidy-Buddy.git", "https://github.com/ZenanXing/Tidy-Buddy.git"), ")")
)
