
# Load the required packages ----------------------------------------------

library(shiny)
library(rhandsontable)
library(bslib) # theme
library(tidyverse)
library(openxlsx)

# Create two containers ---------------------------------------------------

## Card 1 - Original Data --------------------------------------------------

card1 <- card(
  full_screen = TRUE,
  # Header
  card_header(div(style = "text-align: center;", tags$b("Original Data"))),
  # Dimension
  h6(tags$b("Table Info.")),
  textInput(inputId = "n_tb", label = "- Number of tables", value = 6),
  p("- Dimension"),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -15px;",
    textInput(inputId = "col", label = "Column", value = 12),
    textInput(inputId = "row", label = "Row", value = 8)
  ),
  # Variable
  h6(tags$b("Variable Info.")),
  div(style = "margin-top: -20px"),
  textInput(inputId = "n_var", label = "- Number of variables", value = 4),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -10px;",
    uiOutput("var_no_ui"),
    uiOutput("var_nms_ui"),
    uiOutput("var_tps_ui")
  ),
  # Input data
  h6(tags$b("Input Data:")),
  div(
    style = "display: flex; gap: 20px; align-items: flex-start; margin-top: -10px;",
    uiOutput("tb_no_ui"),
    uiOutput("var_slt_ui")
  ),
  div(style = "overflow-x: auto; max-width: 800px; max-height: 800px;",
      uiOutput("var_layout_ui")),
  # Confirm the input
  div(style = "margin-top: 10px"), 
  div(style = "text-align: right;",
      actionButton(inputId = "Trsfm_Butn",
                   label = "Transform it!"))
)

## Card 2 - Tidy Format ----------------------------------------------------

card2 <- navset_card_tab(
  full_screen = TRUE,
  # Header
  title = tags$b("Tidy Format"),
  nav_panel(
    title = "Tidy Data",
    # Inspect the results:
    h6(tags$b("Tidy Table")),
    DT::dataTableOutput("tidy_tb") %>% shinycssloaders::withSpinner(), 
    # Download the table:
    uiOutput(outputId = "dl")
  ),
  nav_panel(
    title = "For IGGYPOPseq", 
    ## Tidy data:
    h6(tags$b("- Plate Layout Info:")),
    div(style = "margin-top: -30px"), 
    radioButtons(inputId = "tdy_opt",
                 label = "Source:",
                 choices = c("Generated by the app" = "tdy_gnrt",
                             "Upload the file" = "tdy_upld"),
                 selected = "tdy_gnrt",
                 inline = TRUE),
    conditionalPanel(condition = "input.tdy_opt == 'tdy_upld'", 
                     fileInput(inputId = "file", 
                               label = NULL), 
                     div(style = "margin-top: -30px"),
                     p("Note: The information for 'primer_index', 'Replicate', 'PrimerPlate', and 'PrimerWell' should be included with the exact column names.")
    ),
    
    ## Reference data:
    #div(style = "margin-top: 10px"), 
    fileInput(inputId = "ref_file", 
              label = h6(tags$b("- Reference Info:"))),
    div(style = "margin-top: -30px"), 
    radioButtons(inputId = "cds_opt",
                 label = h6("CDS:"),
                 choices = c("Yes" = "y",
                             "No" = "n"),
                 selected = "n",
                 inline = TRUE),
    p("Note: The information for 'primer_index', 'n_frags', 'Reference', and 'ReferenceSequence' should be included with the exact column names. If your sequences are CDS sequences, 'CDS_length' should also be included."),
    
    ## Primer data:
    h6(tags$b("- Primer & Barcode Info:")),
    div(style = "margin-top: -30px"), 
    radioButtons(inputId = "prr_slt", 
                 label = "Source:", 
                 choices = c("Select the target vector" = "slt",
                             "Upload the file" = "upld"),
                 selected = "slt",
                 inline = TRUE),
    conditionalPanel(condition = "input.prr_slt == 'slt'",
                     selectInput(inputId = "prr_plt", 
                                 label = NULL, 
                                 choices = c("pPOP" = "pop",
                                             "pPlantPOP" = "pltpop"))
                     ), 
    conditionalPanel(condition = "input.prr_slt == 'upld'",
                     fileInput(inputId = "prr_file", label = NULL),
                     div(style = "margin-top: -30px"), 
                     p("Note: The information for 'PrimerPlate', 'PrimerWell', 'Fwindex', 'FwPrimer', 'Rvindex', and 'RvPrimer' should be included with the exact column names.")
                     ),
    div(style = "margin-top: -20px"), 
    div(style = "text-align: right;",
        actionButton(inputId = "Gnrt_Butn",
                     label = "Generate")), 
    # Inspect the results:
    h6(tags$b("- Sample Info:")),
    DT::dataTableOutput("iggypop_smp_info") %>% shinycssloaders::withSpinner(), 
    # Download the table:
    uiOutput(outputId = "iggypop_dl")
  )
)

# Arrange both cards ------------------------------------------------------

page_fillable(
  
  tags$head(
    tags$style(HTML("
            html {
                transform: scale(0.75);
                transform-origin: top left;
                width: 133.33%;
            }
        "))
  ),
  # Theme
  theme = bs_theme(bootswatch = "minty"),
  
  tags$head(
    tags$title("Tidy Buddy")  # This sets the title of the webpage
  ),

  # Application title
  titlePanel(div(style = "text-align: center;", "Tidy Buddy")),
  
  layout_column_wrap(
    width = 1/2,
    card1, card2
  ),
  h6(tags$b("Source code:")),
  div(style = "margin-top: -40px"), 
  p("The source code, along with the example data, is available via the GitHub repository (", a(href = "https://github.com/ZenanXing/Tidy-Buddy.git", "https://github.com/ZenanXing/Tidy-Buddy.git"), ")")
)
